fix: //rs/tests/nested:guestos_upgrade tests (#8309)
This fixes the tests:

* `//rs/tests/nested:guestos_upgrade_from_latest_release_to_current`
*
`//rs/tests/nested:guestos_upgrade_from_latest_release_to_current_head_nns`
* `//rs/tests/nested:guestos_upgrade_smoke_test`
* `//rs/tests/nested:guestos_upgrade_smoke_test_head_nns`

which all started failing after 70fb598fea6165ff9303b07777984ddbc27b0f95
with:

```
2026-01-12 04:09:07.478 INFO[upgrade_guestos:StdErr] thread 'main' panicked at external/rules_rust~~crate~crate_index__tokio-1.48.0/src/runtime/blocking/shutdown.rs:51:21:
2026-01-12 04:09:07.478 INFO[upgrade_guestos:StdErr] Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.
2026-01-12 04:09:07.478 INFO[upgrade_guestos:StdErr] stack backtrace:
2026-01-12 04:09:07.478 INFO[upgrade_guestos:StdErr]    0:     0x5663672c9352 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hdcfcb6d4c8489523
2026-01-12 04:09:07.478 INFO[upgrade_guestos:StdErr]    1:     0x5663672f9533 - core::fmt::write::h8a494366950f23bb
2026-01-12 04:09:07.478 INFO[upgrade_guestos:StdErr]    2:     0x5663672c3853 - std::io::Write::write_fmt::h6556609fca33d0b1
2026-01-12 04:09:07.479 INFO[upgrade_guestos:StdErr]    3:     0x5663672c91a2 - std::sys::backtrace::BacktraceLock::print::hb2a626a81e06b2dc
2026-01-12 04:09:07.479 INFO[upgrade_guestos:StdErr]    4:     0x5663672cb683 - std::panicking::default_hook::{{closure}}::h4f78485264f12d10
2026-01-12 04:09:07.479 INFO[upgrade_guestos:StdErr]    5:     0x5663672cb465 - std::panicking::default_hook::h2c66fc99e962531d
2026-01-12 04:09:07.479 INFO[upgrade_guestos:StdErr]    6:     0x5663672cc095 - std::panicking::rust_panic_with_hook::h33ac55f64bbd807d
2026-01-12 04:09:07.479 INFO[upgrade_guestos:StdErr]    7:     0x5663672cbdf6 - std::panicking::begin_panic_handler::{{closure}}::h30e7cb89678a57fe
2026-01-12 04:09:07.479 INFO[upgrade_guestos:StdErr]    8:     0x5663672c9859 - std::sys::backtrace::__rust_end_short_backtrace::hed60f27456c16ced
2026-01-12 04:09:07.479 INFO[upgrade_guestos:StdErr]    9:     0x5663672cbabd - __rustc[de2ca18b4c54d5b8]::rust_begin_unwind
2026-01-12 04:09:07.479 INFO[upgrade_guestos:StdErr]   10:     0x5663672f6360 - core::panicking::panic_fmt::h62f63d096dd276af
2026-01-12 04:09:07.479 INFO[upgrade_guestos:StdErr]   11:     0x5663672187ff - tokio::runtime::blocking::pool::BlockingPool::shutdown::h8b2024730f607e92
2026-01-12 04:09:07.479 INFO[upgrade_guestos:StdErr]   12:     0x566366db1bae - core::ptr::drop_in_place<tokio::runtime::blocking::pool::BlockingPool>::hc6c6804c09255b85
2026-01-12 04:09:07.479 INFO[upgrade_guestos:StdErr]   13:     0x566366dbc5de - reqwest::blocking::wait::enter::h64bf75aee7e74f3c
2026-01-12 04:09:07.479 INFO[upgrade_guestos:StdErr]   14:     0x566366dba8ec - reqwest::blocking::wait::timeout::ha7354576a6b6309f
2026-01-12 04:09:07.479 INFO[upgrade_guestos:StdErr]   15:     0x566366d9309a - reqwest::blocking::client::ClientBuilder::build::h2d7c7d8a8289ad1b
2026-01-12 04:09:07.479 INFO[upgrade_guestos:StdErr]   16:     0x5663651784ec - ic_system_test_driver::driver::test_env_api::HasPublicApiUrl::is_orchestrator_dashboard_accessible::h1acffaa1e50f741d
2026-01-12 04:09:07.479 INFO[upgrade_guestos:StdErr]   17:     0x5663651bcce0 - ic_system_test_driver::driver::test_env_api::retry::hd56ea1e7e0a134e6
2026-01-12 04:09:07.479 INFO[upgrade_guestos:StdErr]   18:     0x566365178c63 - ic_system_test_driver::driver::test_env_api::HasPublicApiUrl::await_orchestrator_dashboard_accessible::h4f0bd1618f5f6041
2026-01-12 04:09:07.479 INFO[upgrade_guestos:StdErr]   19:     0x566365175847 - guestos_upgrade_test_bin::upgrade_guestos::{{closure}}::h2effb879f57b3b2e
2026-01-12 04:09:07.479 INFO[upgrade_guestos:StdErr]   20:     0x56636515bff7 - tokio::runtime::park::CachedParkThread::block_on::h74478075076f729c
2026-01-12 04:09:07.479 INFO[upgrade_guestos:StdErr]   21:     0x5663651dd2ac - tokio::runtime::context::runtime::enter_runtime::h058b9d83967ed6cc
2026-01-12 04:09:07.479 INFO[upgrade_guestos:StdErr]   22:     0x5663651a809d - tokio::runtime::runtime::Runtime::block_on::h56f50b02f338a200
2026-01-12 04:09:07.480 INFO[upgrade_guestos:StdErr]   23:     0x5663651af766 - ic_system_test_driver::util::block_on::hd9018313831709d4
2026-01-12 04:09:07.480 INFO[upgrade_guestos:StdErr]   24:     0x5663651beb6a - core::ops::function::FnOnce::call_once{{vtable.shim}}::hc49b6e1567b2f475
2026-01-12 04:09:07.480 INFO[upgrade_guestos:StdErr]   25:     0x566365522843 - core::ops::function::FnOnce::call_once{{vtable.shim}}::he5d67dc1eb74ce17
2026-01-12 04:09:07.480 INFO[upgrade_guestos:StdErr]   26:     0x56636553fc3d - <ic_system_test_driver::driver::subprocess_task::SubprocessTask as ic_system_test_driver::driver::task::Task>::execute::h3b997660a54a3a22
2026-01-12 04:09:07.480 INFO[upgrade_guestos:StdErr]   27:     0x5663654c74fe - ic_system_test_driver::driver::group::SystemTestGroup::execute::he64a144ab5c67a8f
2026-01-12 04:09:07.480 INFO[upgrade_guestos:StdErr]   28:     0x5663654c88f8 - ic_system_test_driver::driver::group::SystemTestGroup::execute_from_args::h27bd517c0833dfb4
2026-01-12 04:09:07.480 INFO[upgrade_guestos:StdErr]   29:     0x5663651c729f - guestos_upgrade_test_bin::main::h815520975948ca3f
2026-01-12 04:09:07.480 INFO[upgrade_guestos:StdErr]   30:     0x5663651ebac3 - std::sys::backtrace::__rust_begin_short_backtrace::h3c12092f900fae04
2026-01-12 04:09:07.480 INFO[upgrade_guestos:StdErr]   31:     0x5663651c987d - std::rt::lang_start::{{closure}}::h285455ddd97dc36e
2026-01-12 04:09:07.480 INFO[upgrade_guestos:StdErr]   32:     0x5663672b82b0 - std::rt::lang_start_internal::h34f9328d113fd60a
2026-01-12 04:09:07.480 INFO[upgrade_guestos:StdErr]   33:     0x5663651c7405 - main
2026-01-12 04:09:07.480 INFO[upgrade_guestos:StdErr]   34:     0x7d5d59adb1ca - <unknown>
2026-01-12 04:09:07.480 INFO[upgrade_guestos:StdErr]   35:     0x7d5d59adb28b - __libc_start_main
2026-01-12 04:09:07.480 INFO[upgrade_guestos:StdErr]   36:     0x566364ffe7aa - _start
```