fix(IDX): remove IDMAP (#8521)
This PR https://github.com/dfinity/ic/pull/7983 introduced the error 
```
Error: OCI runtime error: crun: mkdir `/ic/.aws`: Value too large for defined data type
``` 
and does not seem to be needed for the regular container run. I ran
`bazel build //ic-os/guestos/envs/prod:disk-img.tar.zs` to test and that
built successfully. If it turns out this is needed we can find another
way to id IDMAPs back - but this is causing too many issues in other
places that we need to remove it.

---------

Co-authored-by: IDX GitHub Automation <infra+github-automation@dfinity.org>