chore(ICP_Rosetta): DEFI-2459: Improve ICP Rosetta logging and errors (#7625)
Add more details to the error message that is logged on the server side,
and returned to the client, for the `construction/payloads` endpoint of
ICP Rosetta. Also add some more detailed debug logging where the error
occurs, to facilitate debugging.
E.g.,
```
2025-11-11T18:25:05.319170Z DEBUG rs/rosetta-api/icp/src/convert.rs:150: Error parsing operation type 'TRANSFER': Matching variant not found
2025-11-11T18:25:05.319465Z ERROR rs/rosetta-api/icp/src/rosetta_server.rs:213: Internal error: Error(Error { code: 730, message: "An invalid transaction has been detected", description: None, retriable: false, details: Some({"error_message": String("Error parsing operation type 'TRANSFER': Matching variant not found")}) })
```

instead of
```
2025-11-10T06:44:18.428798Z ERROR rs/rosetta-api/icp/src/rosetta_server.rs:213: Internal error: Error(Error { code: 700, message: "Internal server error", description: None, retriable: false, details: Some({"error_message": String("Failed to parse string: VariantNotFound")}) })
```