test: CON-1417 Enable VetKD in large subnet recovery test (#5213)
The large subnet recovery test now passes with VetKD, after chunking of
registry deltas was enabled on master.

The test can be executed using:
```bash
ict test //rs/tests/consensus/subnet_recovery:sr_app_large_with_chain_key_test_head_nns_colocate
```

Previously, the registry canister would panic with the following message
instead:
```
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] Panicked at '[Registry] Transaction rejected because delta would be too large: 2257731 vs 1398101.', rs/registry/canister/src/registry.rs:430:13
```

Additionally, we reduce the DKG interval of recovery test down to 14,
now that the vet Key is reshared from a subnet other than the NNS.