chore: bind mount ~/.cache/zig-cache to /tmp/zig-cache (#5270)
On `zh-spm34` and `zh1-spm22` when running
`ci/container/container-run.sh` the podman option:
```
--mount type=volume,chown=true,destination=/tmp/zig-cache
```
causes:
```
Error: 'overlay' is not supported over zfs
```
and 
```
Error: chown: invalid mount option
```
So instead of using a volume to mount `/tmp/zig-cache` we bind mount
`~/.cache/zig-cache` to `/tmp/zig-cache` in both
`ci/container/container-run.sh` and `.devcontainer/devcontainer.json`.