test(sns): Tests opt in to test-only features of Governance. (#11700)
## Motivation

There are a couple of PRs (external contributions, but this fact is
incidental) that are blocked due to the SNS Governance WASM in test
being too large. E.g. in [PR 11078],
`//rs/sns/integration_tests:upgrade_canister_test` fails like so

```
looking up sns-governance-canister at SNS_GOVERNANCE_CANISTER_WASM_PATH
Using pre-built binary for sns-governance-canister with features: [] (size = 2026015, path = rs/sns/governance/sns-governance-canister-test.wasm.gz)
thread 'test_upgrade_after_state_shrink' (18) panicked at rs/sns/integration_tests/src/upgrade_canister.rs:664:14:
called `Result::unwrap()` on an `Err` value: GovernanceError { error_type: InvalidProposal, error_message: "1 defects in Proposal:\nUpgradeSnsControlledCanister was invalid for the following reason(s):\nthe maximum canister WASM and argument size for UpgradeSnsControlledCanister is 2000000 bytes." }
stack backtrace:
... ELIDED ...
failures:
    test_upgrade_after_state_shrink
test result: FAILED. 6 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 296.00s
```

[PR 11078]: https://github.com/dfinity/ic/pull/11078

This does not address the fact that WASMs are getting large.

Regardless, I have confirmed that if PR 11078 had these changes, the
aforementioned test would pass. Therefore, the plan is, merge this, then
have PR 11078 (and others like it) merge one last time, and hopefully,
they can then go in. Separately, we will look into either shrinking this
WASM, or chunking.

---------

Co-authored-by: Daniel Wong <daniel.wong@dfinity.org>
Co-authored-by: IDX GitHub Automation <infra+github-automation@dfinity.org>