Only run //rs/tests/message_routing:queues_compatibility_test on farm for now
The test fails on the local backend because it downloads the mainnet
replicated-state-test/state-layout-test binaries from an external URL and we
don't allow network access for local tests:

  thread 'main' panicked at rs/tests/message_routing/queues_compatibility_test.rs:102:6:
  Failed to Download: ... Error: error sending request for url
    (https://download.dfinity.systems/ic/<version>/release/replicated-state-test.gz)

To support this locally the mainnet test binaries would have to be provided via
a bazel dependency instead of being downloaded from the CDN.