chore: use ic-cdk 0.18.0-alpha.2 (#5363)
Recalculating the `Cargo.Bazel.*` files by emptying them and running
`bin/bazel-pin.sh --force` results in:
```
error: failed to select a version for the requirement `ic-cdk = "^0.18.0"`
  version 0.18.0 is yanked
  version 0.18.1 is yanked
  version 0.18.2 is yanked
```
This is because [the following
targets](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/dfinity/ic%24+%27ic-cdk+%3D+%220.18.0%22%27&patternType=keyword&sm=0)
were still depending on `ic-cdk = "^0.18.0"`:
* `//rs/rust_canisters/downstream_calls_test`
* `//rs/rust_canisters/random_traffic_test`
* `//rs/rust_canisters/xnet_test`

This is fixed by letting those targets depend on ic-cdk--0.18.0-alpha.2.