refactor(sns-cli): Use anyhow (#1120)
## Problem

It is generally not a very good practice to perform an `.unwrap()` that
might plausibly fail, outside of tests. Instead, it is better to return
an error. Even in the `main` function, you can return a `Result` instead
of using `.unwrap()` or `exit(1)` (and returning an `Err` from the main
function will automatically set a non-zero exit code). Using `exit(1)`
is particularly dangerous as you may forget to call it, or forget to use
`eprintln!` instead of `println!`, in both cases doing something
somewhat unexpected that the compiler will not warn you about.

## Solution

Convert all the sns-cli endpoints to return an `anyhow::Result` instead
of `()`. This enables them to return errors instead of panicking.

## Impoved code 

### Example 1

Using anyhow makes some of our code a bit more concise as well. For
example, compare the original:

```rust
let sns_init_payload = args.generate_sns_init_payload().unwrap_or_else(|err| {
    eprintln!(
        "Error encountered when generating the SnsInitPayload: {}",
        err
    );
    exit(1);
});
```

with:

```rust
let sns_init_payload = args
    .generate_sns_init_payload()
    .context("Generating the SnsInitPayload")?;
```

Which is not exactly equivalent, but the latter returns a (imho) nicer
error message. For the unfamiliar,

```
use anyhow::{anyhow, context};
fn main() {
    return Err(anyhow!("What went wrong.")).context("Error situation");
}
```

outputs:

```
Error: Error situation

Caused by:
    What went wrong.
```

Using `.context()` gives us something that's almost like a
human-readable backtrace:

```rust
use anyhow::{anyhow, Context};
fn main() {
    return Err(anyhow!("What went wrong."))
        .context("I think something is about to go wrong")
        .context("Error situation");
}
```
 
outputs:
 
```
Error: Error situation

Caused by:
    0: I think something is about to go wrong
    1: What went wrong.
```

### Example 2

```rust
if let Some(save_to) = &save_to {
    if let Err(err) = ensure_file_exists_and_is_writeable(save_to.as_path()) {
        eprintln!("{}", err);
        std::process::exit(1);
    }
}
```

Becomes

```rust
if let Some(save_to) = &save_to {
    ensure_file_exists_and_is_writeable(save_to.as_path())?
}
```


## Additional notes

I have not actually removed all the occurrences of `.unwrap()` yet, but
I have updated all the cases where we called `exit(1)`.