running #1 in parallel with potential non-deterministic behavior; unexpected failure on the 2nd test CanisterError, reject_message: \"Error from Canister 5v3p4-iyaaa-aaaaa-qaaaa-cai: Canister 5v3p4-iyaaa-aaaaa-qaaaa-cai is out of cycles
2025-04-08 12:51:42.790 INFO[test_request_with_refund_expectation:StdErr] gbrel balance before: 99999136720532
2025-04-08 12:51:42.790 INFO[test_request_with_refund_expectation:StdOut] gbrel balance before: 99999136720532
2025-04-08 12:51:42.790 INFO[test_request_with_refund_expectation:StdErr] computed expected cost: 6413062400
2025-04-08 12:51:42.790 INFO[test_request_with_refund_expectation:StdOut] computed expected cost: 6413062400
2025-04-08 12:51:42.792 DEBG[test_request_with_refund_expectation:rs/tests/driver/src/driver/test_env_api.rs:2074:0] Func="await_status_is_healthy of http://[2602:fb2b:110:10:50d5:b8ff:fe35:dd51]:8080/ [rs/tests/driver/src/driver/test_env_api.rs:1622]" is being retried for the maximum of 500s with a linear backoff of 5s
2025-04-08 12:51:42.824 DEBG[test_request_with_refund_expectation:rs/tests/driver/src/driver/test_env_api.rs:2081:0] Func="await_status_is_healthy of http://[2602:fb2b:110:10:50d5:b8ff:fe35:dd51]:8080/ [rs/tests/driver/src/driver/test_env_api.rs:1622]" succeeded after 32.274092ms on attempt 1
2025-04-08 12:51:43.850 INFO[test_request_with_refund_expectation:StdErr] thread 'main' panicked at rs/tests/networking/canister_http_correctness_test.rs:293:5:
2025-04-08 12:51:43.850 INFO[test_request_with_refund_expectation:StdErr] assertion failed: `Err(RejectResponse { reject_code: CanisterError, reject_message: "Error from Canister 5v3p4-iyaaa-aaaaa-qaaaa-cai: Canister 5v3p4-iyaaa-aaaaa-qaaaa-cai is out of cycles", error_code: Some("IC0504") })` does not match `Ok(r) if r.status==200`
2025-04-08 12:51:43.851 INFO[test_request_with_refund_expectation:StdErr] stack backtrace:
2025-04-08 12:51:43.862 INFO[test_request_with_refund_expectation:StdErr]    0:     0x5675dc2fb77a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::ha4a311b32f6b4ad8
2025-04-08 12:51:43.862 INFO[test_request_with_refund_expectation:StdErr]    1:     0x5675dc32ca73 - core::fmt::write::h1866771663f62b81
2025-04-08 12:51:43.862 INFO[test_request_with_refund_expectation:StdErr]    2:     0x5675dc2f61a3 - std::io::Write::write_fmt::hb549e7444823135e
2025-04-08 12:51:43.862 INFO[test_request_with_refund_expectation:StdErr]    3:     0x5675dc2fb5c2 - std::sys::backtrace::BacktraceLock::print::hddd3a9918ce29aa7
2025-04-08 12:51:43.862 INFO[test_request_with_refund_expectation:StdErr]    4:     0x5675dc2fcefc - std::panicking::default_hook::{{closure}}::h791f75256b902d7d
2025-04-08 12:51:43.862 INFO[test_request_with_refund_expectation:StdErr]    5:     0x5675dc2fcd42 - std::panicking::default_hook::h82cc572fcb0d8cd7
2025-04-08 12:51:43.862 INFO[test_request_with_refund_expectation:StdErr]    6:     0x5675dc2fd537 - std::panicking::rust_panic_with_hook::he21644cc2707f2c4
2025-04-08 12:51:43.862 INFO[test_request_with_refund_expectation:StdErr]    7:     0x5675dc2fd3ca - std::panicking::begin_panic_handler::{{closure}}::h42f7c414fed3cad9
2025-04-08 12:51:43.862 INFO[test_request_with_refund_expectation:StdErr]    8:     0x5675dc2fbc59 - std::sys::backtrace::__rust_end_short_backtrace::ha26cf5766b4e8c65
2025-04-08 12:51:43.862 INFO[test_request_with_refund_expectation:StdErr]    9:     0x5675dc2fd05c - rust_begin_unwind
2025-04-08 12:51:43.863 INFO[test_request_with_refund_expectation:StdErr]   10:     0x5675dc329d90 - core::panicking::panic_fmt::h74866b78e934b1c0
2025-04-08 12:51:43.863 INFO[test_request_with_refund_expectation:StdErr]   11:     0x5675da6667ae - canister_http_correctness_test_bin::test_request_with_refund_expectation::h369e0a4a0a1c3e4e
2025-04-08 12:51:43.863 INFO[test_request_with_refund_expectation:StdErr]   12:     0x5675da89082a - core::ops::function::FnOnce::call_once{{vtable.shim}}::h71d874bc4e0f6ff0
2025-04-08 12:51:43.863 INFO[test_request_with_refund_expectation:StdErr]   13:     0x5675da8ba233 - <ic_system_test_driver::driver::subprocess_task::SubprocessTask as ic_system_test_driver::driver::task::Task>::execute::hdfc083c0293515d8
2025-04-08 12:51:43.863 INFO[test_request_with_refund_expectation:StdErr]   14:     0x5675daad7fb1 - ic_system_test_driver::driver::group::SystemTestGroup::execute::hf267ecdc835c2654
2025-04-08 12:51:43.863 INFO[test_request_with_refund_expectation:StdErr]   15:     0x5675daad9896 - ic_system_test_driver::driver::group::SystemTestGroup::execute_from_args::hacaf5214f39b360c
2025-04-08 12:51:43.863 INFO[test_request_with_refund_expectation:StdErr]   16:     0x5675da6652bd - canister_http_correctness_test_bin::main::h41d851314b98c10e
2025-04-08 12:51:43.863 INFO[test_request_with_refund_expectation:StdErr]   17:     0x5675da65e3b3 - std::sys::backtrace::__rust_begin_short_backtrace::h81ad7d0624510f7b
2025-04-08 12:51:43.863 INFO[test_request_with_refund_expectation:StdErr]   18:     0x5675da658d6d - std::rt::lang_start::{{closure}}::h346cf1bd0d6cb78c
2025-04-08 12:51:43.863 INFO[test_request_with_refund_expectation:StdErr]   19:     0x5675dc2eadc7 - std::rt::lang_start_internal::h78dd36c15a6b42b8
2025-04-08 12:51:43.863 INFO[test_request_with_refund_expectation:StdErr]   20:     0x5675da666f95 - main
2025-04-08 12:51:43.863 INFO[test_request_with_refund_expectation:StdErr]   21:     0x7a201e722083 - __libc_start_main
2025-04-08 12:51:43.863 INFO[test_request_with_refund_expectation:StdErr]   22:     0x5675da5c796e - _start
2025-04-08 12:51:43.863 INFO[test_request_with_refund_expectation:StdErr]   23:                0x0 - <unknown>
2025-04-08 12:51:43.864 WARN[test_request_with_refund_expectation:rs/tests/driver/src/driver/subprocess_ipc.rs:68:0] [Function panicked]: assertion failed: `Err(RejectResponse { reject_code: CanisterError, reject_message: "Error from Canister 5v3p4-iyaaa-aaaaa-qaaaa-cai: Canister 5v3p4-iyaaa-aaaaa-qaaaa-cai is out of cycles", error_code: Some("IC0504") })` does not match `Ok(r) if r.status==200`
2025-04-08 12:51:43.864 INFO[test_request_with_refund_expectation:StdErr] thread 'main' panicked at rs/tests/driver/src/driver/group.rs:947:35:
2025-04-08 12:51:43.864 INFO[test_request_with_refund_expectation:StdErr] called `Result::unwrap()` on an `Err` value: "assertion failed: `Err(RejectResponse { reject_code: CanisterError, reject_message: \"Error from Canister 5v3p4-iyaaa-aaaaa-qaaaa-cai: Canister 5v3p4-iyaaa-aaaaa-qaaaa-cai is out of cycles\", error_code: Some(\"IC0504\") })` does not match `Ok(r) if r.status==200`"
2025-04-08 12:51:43.864 INFO[test_request_with_refund_expectation:StdErr] stack backtrace:
2025-04-08 12:51:43.864 INFO[test_request_with_refund_expectation:StdErr]    0:     0x5675dc2fb77a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::ha4a311b32f6b4ad8
2025-04-08 12:51:43.864 INFO[test_request_with_refund_expectation:StdErr]    1:     0x5675dc32ca73 - core::fmt::write::h1866771663f62b81
2025-04-08 12:51:43.864 INFO[test_request_with_refund_expectation:StdErr]    2:     0x5675dc2f61a3 - std::io::Write::write_fmt::hb549e7444823135e
2025-04-08 12:51:43.864 INFO[test_request_with_refund_expectation:StdErr]    3:     0x5675dc2fb5c2 - std::sys::backtrace::BacktraceLock::print::hddd3a9918ce29aa7
2025-04-08 12:51:43.864 INFO[test_request_with_refund_expectation:StdErr]    4:     0x5675dc2fcefc - std::panicking::default_hook::{{closure}}::h791f75256b902d7d
2025-04-08 12:51:43.864 INFO[test_request_with_refund_expectation:StdErr]    5:     0x5675dc2fcd42 - std::panicking::default_hook::h82cc572fcb0d8cd7
2025-04-08 12:51:43.865 INFO[test_request_with_refund_expectation:StdErr]    6:     0x5675dc2fd537 - std::panicking::rust_panic_with_hook::he21644cc2707f2c4
2025-04-08 12:51:43.865 INFO[test_request_with_refund_expectation:StdErr]    7:     0x5675dc2fd3ca - std::panicking::begin_panic_handler::{{closure}}::h42f7c414fed3cad9
2025-04-08 12:51:43.865 INFO[test_request_with_refund_expectation:StdErr]    8:     0x5675dc2fbc59 - std::sys::backtrace::__rust_end_short_backtrace::ha26cf5766b4e8c65
2025-04-08 12:51:43.865 INFO[test_request_with_refund_expectation:StdErr]    9:     0x5675dc2fd05c - rust_begin_unwind
2025-04-08 12:51:43.865 INFO[test_request_with_refund_expectation:StdErr]   10:     0x5675dc329d90 - core::panicking::panic_fmt::h74866b78e934b1c0
2025-04-08 12:51:43.865 INFO[test_request_with_refund_expectation:StdErr]   11:     0x5675dc32a1d6 - core::result::unwrap_failed::h899ed7ab2ccb8159
2025-04-08 12:51:43.865 INFO[test_request_with_refund_expectation:StdErr]   12:     0x5675daad8ac6 - ic_system_test_driver::driver::group::SystemTestGroup::execute::hf267ecdc835c2654
2025-04-08 12:51:43.865 INFO[test_request_with_refund_expectation:StdErr]   13:     0x5675daad9896 - ic_system_test_driver::driver::group::SystemTestGroup::execute_from_args::hacaf5214f39b360c
2025-04-08 12:51:43.865 INFO[test_request_with_refund_expectation:StdErr]   14:     0x5675da6652bd - canister_http_correctness_test_bin::main::h41d851314b98c10e
2025-04-08 12:51:43.865 INFO[test_request_with_refund_expectation:StdErr]   15:     0x5675da65e3b3 - std::sys::backtrace::__rust_begin_short_backtrace::h81ad7d0624510f7b
2025-04-08 12:51:43.865 INFO[test_request_with_refund_expectation:StdErr]   16:     0x5675da658d6d - std::rt::lang_start::{{closure}}::h346cf1bd0d6cb78c
2025-04-08 12:51:43.865 INFO[test_request_with_refund_expectation:StdErr]   17:     0x5675dc2eadc7 - std::rt::lang_start_internal::h78dd36c15a6b42b8
2025-04-08 12:51:43.865 INFO[test_request_with_refund_expectation:StdErr]   18:     0x5675da666f95 - main
2025-04-08 12:51:43.865 INFO[test_request_with_refund_expectation:StdErr]   19:     0x7a201e722083 - __libc_start_main
2025-04-08 12:51:43.865 INFO[test_request_with_refund_expectation:StdErr]   20:     0x5675da5c796e - _start
2025-04-08 12:51:43.865 INFO[test_request_with_refund_expectation:StdErr]   21:                0x0 - <unknown>
2025-04-08 12:51:43.870 INFO[rs/tests/driver/src/driver/process.rs:115:9] (test_request_with_refund_expectation|StdOut): Channel has closed.
2025-04-08 12:51:43.870 INFO[rs/tests/driver/src/driver/process.rs:115:9] (test_request_with_refund_expectation|StdErr): Channel has closed.
2025-04-08 12:51:43.870 INFO[rs/tests/driver/src/driver/subprocess_task.rs:95:17] Task 'test_request_with_refund_expectation' finished with exit code: Ok(ExitStatus(unix_wait_status(25856)))
2025-04-08 12:51:43.870 DEBG[rs/tests/driver/src/driver/task_scheduler.rs:133:21] Task Test("test_request_with_refund_expectation") failed due to: assertion failed: `Err(RejectResponse { reject_code: CanisterError, reject_message: "Error from Canister 5v3p4-iyaaa-aaaaa-qaaaa-cai: Canister 5v3p4-iyaaa-aaaaa-qaaaa-cai is out of cycles", error_code: Some("IC0504") })` does not match `Ok(r) if r.status==200`
2025-04-08 12:51:43.870 DEBG[rs/tests/driver/src/driver/subprocess_task.rs:219:17] Task 'test_request_with_refund_expectation' already terminated!
2025-04-08 12:51:44.901 INFO[rs/tests/driver/src/driver/process.rs:115:9] (test_request_with_more_cycles_than_canister|StdOut): Channel has closed.
2025-04-08 12:51:44.901 INFO[rs/tests/driver/src/driver/process.rs:115:9] (test_request_with_more_cycles_than_canister|StdErr): Channel has closed.
2025-04-08 12:51:44.901 INFO[rs/tests/driver/src/driver/subprocess_task.rs:95:17] Task 'test_request_with_more_cycles_than_canister' finished with exit code: Ok(ExitStatus(unix_wait_status(0)))
2025-04-08 12:51:44.901 DEBG[rs/tests/driver/src/driver/task_scheduler.rs:121:21] Task Test("test_request_with_more_cycles_than_canister") succeeded due to: Exited with code 0.
2025-04-08 12:51:44.902 INFO[rs/tests/driver/src/driver/process.rs:110:21] (uvms_logs_stream|StdErr): Kill received.
2025-04-08 12:51:44.902 INFO[rs/tests/driver/src/driver/process.rs:110:21] (uvms_logs_stream|StdOut): Kill received.
2025-04-08 12:51:44.904 INFO[rs/tests/driver/src/driver/subprocess_task.rs:95:17] Task 'uvms_logs_stream' finished with exit code: Ok(ExitStatus(unix_wait_status(9)))
2025-04-08 12:51:44.904 INFO[rs/tests/driver/src/driver/process.rs:110:21] (keepalive|StdOut): Kill received.
2025-04-08 12:51:44.904 INFO[rs/tests/driver/src/driver/process.rs:110:21] (keepalive|StdErr): Kill received.
2025-04-08 12:51:44.907 INFO[rs/tests/driver/src/driver/subprocess_task.rs:95:17] Task 'keepalive' finished with exit code: Ok(ExitStatus(unix_wait_status(9)))
2025-04-08 12:51:44.908 DEBG[rs/tests/driver/src/driver/subprocess_task.rs:219:17] Task 'test_request_with_more_cycles_than_canister' already terminated!
2025-04-08 12:51:44.908 INFO[rs/tests/driver/src/driver/task_scheduler.rs:107:17] Task scheduler is out of running tasks and will terminate.
2025-04-08 12:51:44.908 INFO[rs/tests/driver/src/driver/group.rs:911:17] Task scheduler has terminated.
2025-04-08 12:51:44.908 INFO[rs/tests/driver/src/driver/log_events.rs:20:9] {"event_name":"json_report_created_event","body":{"test_name":"canister_http_correctness_test","success":[{"name":"setup","runtime":64.632665963,"message":"Exited with code 0."},{"name":"test_request_with_more_cycles_than_canister","runtime":3.214826527,"message":"Exited with code 0."}],"failure":[{"name":"test_request_with_refund_expectation","runtime":2.176703147,"message":"assertion failed: `Err(RejectResponse { reject_code: CanisterError, reject_message: \"Error from Canister 5v3p4-iyaaa-aaaaa-qaaaa-cai: Canister 5v3p4-iyaaa-aaaaa-qaaaa-cai is out of cycles\", error_code: Some(\"IC0504\") })` does not match `Ok(r) if r.status==200`"}],"skipped":[]}}
2025-04-08 12:51:44.908 INFO[rs/tests/driver/src/driver/group.rs:926:21] Report:
=================================================================== Summary for //rs/tests/networking:canister_http_correctness_test ===================================================================
Task setup                                       PASSED  in  64.63s   -- Exited with code 0.
Task test_request_with_more_cycles_than_canister PASSED  in   3.21s   -- Exited with code 0.
Task test_request_with_refund_expectation        FAILED  in   2.18s   -- assertion failed: `Err(RejectResponse { reject_code: CanisterError, reject_message: "Error from Canister 5v3p4-iyaaa-aaaaa-qaaaa-cai: Canister 5v3p4-iyaaa-aaaaa-qaaaa-cai is out of cycles", error_code: Some("IC0504") })` does not match `Ok(r) if r.status==200`
========================================================================================================================================================================================================

2025-04-08 12:51:44.908 INFO[rs/tests/driver/src/driver/group.rs:969:9] Deleting farm group.
2025-04-08 12:51:44.908 TRCE[rs/tests/driver/src/driver/group.rs:290:5] get_setup_env()
2025-04-08 12:51:44.908 DEBG[rs/tests/driver/src/driver/context.rs:211:9] ProcessContext.new
2025-04-08 12:51:44.908 DEBG[rs/tests/driver/src/driver/context.rs:113:9] Ensuring directory "/home/ubuntu/.cache/bazel/_bazel_gbrel/6d065581cce7ad9076e3b8db2b3afaf0/sandbox/processwrapper-sandbox/922/execroot/_main/_tmp/229ca3da075b10dbee918e16474134a3/setup" exists ...
Error: Tests failed: Test driver completed normally, but some tests failed
{"test_name":"canister_http_correctness_test","success":[{"name":"setup","runtime":64.632665963,"message":"Exited with code 0."},{"name":"test_request_with_more_cycles_than_canister","runtime":3.214826527,"message":"Exited with code 0."}],"failure":[{"name":"test_request_with_refund_expectation","runtime":2.176703147,"message":"assertion failed: `Err(RejectResponse { reject_code: CanisterError, reject_message: \"Error from Canister 5v3p4-iyaaa-aaaaa-qaaaa-cai: Canister 5v3p4-iyaaa-aaaaa-qaaaa-cai is out of cycles\", error_code: Some(\"IC0504\") })` does not match `Ok(r) if r.status==200`"}],"skipped":[]}

Stack backtrace:
   0: anyhow::kind::Adhoc::new
   1: ic_system_test_driver::driver::group::SystemTestGroup::execute
   2: ic_system_test_driver::driver::group::SystemTestGroup::execute_from_args
   3: canister_http_correctness_test_bin::main
   4: std::sys::backtrace::__rust_begin_short_backtrace
   5: std::rt::lang_start::{{closure}}
   6: std::rt::lang_start_internal
   7: main
   8: __libc_start_main
   9: _start

Stack backtrace:
   0: anyhow::error::<impl anyhow::Error>::msg
   1: anyhow::__private::format_err
   2: ic_system_test_driver::driver::group::SystemTestGroup::execute_from_args
   3: canister_http_correctness_test_bin::main
   4: std::sys::backtrace::__rust_begin_short_backtrace
   5: std::rt::lang_start::{{closure}}
   6: std::rt::lang_start_internal
   7: main
   8: __libc_start_main
   9: _start
FAIL: //rs/tests/networking:canister_http_correctness_test (see /home/ubuntu/.cache/bazel/_bazel_gbrel/6d065581cce7ad9076e3b8db2b3afaf0/execroot/_main/bazel-out/k8-opt/testlogs/rs/tests/networking/canister_http_correctness_test/test.log)
INFO: Found 1 test target...
Target //rs/tests/networking:canister_http_correctness_test up-to-date:
  bazel-bin/rs/tests/networking/canister_http_correctness_test/run-test.sh
INFO: Elapsed time: 97.130s, Critical Path: 94.22s
INFO: 3 processes: 3 processwrapper-sandbox.
INFO: Build completed, 1 test FAILED, 3 total actions
//rs/tests/networking:canister_http_correctness_test                     FAILED in 88.1s
  /home/ubuntu/.cache/bazel/_bazel_gbrel/6d065581cce7ad9076e3b8db2b3afaf0/execroot/_main/bazel-out/k8-opt/testlogs/rs/tests/networking/canister_http_correctness_test/test.log

Executed 1 out of 1 test: 1 fails locally.
INFO: Streaming build results to: https://dash.idx.dfinity.network/invocation/c2973838-bb98-4b53-afda-17a77b84c9c8
There was an error while executing CLI: exit status 3
λ $