fix(node): more robust guest_vm_runner vm retry logic and better logging (#7073)
NODE-1732

We've seen VM contention logs like the following:
```
Guest VM stopped, restarting
Machine qemu-1-guestos terminated.
Creating GuestOS virtual machine
Assembling config media for GuestOS: /tmp/config_mediavQpdwr
Unable to remove disk metadata on vm guestos from /tmp/config_mediag7h6JB (disk target sda)
operation failed: domain 'guestos' is already being removed
libvirt: Domain Config error : operation failed: domain 'guestos' is already being removed
ERROR: Failed to start GuestOS virtual machine.
Error: Failed to define GuestOS virtual machine
    1: error: operation failed: domain 'guestos' is already being removed [code=operationfailed (9), domain=domain (20)]
```

This fixes the `try_destroy_existing_vm` retry logic, as the libvirt
`Domain Config error : operation failed: domain 'guestos' is already
being removed` error was not triggering the restrictive conditional [in
this
case](https://kibana.testnet.dfinity.network/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:60000),time:(from:'2025-09-30T11:25:22.477Z',to:'2025-09-30T11:35:22.477Z'))&_a=(columns:!(MESSAGE,ic_subnet,ic_node),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,field:ic,index:testnet-vector-push,key:ic,negate:!f,params:(query:nr-broken-dfinity-node-head-nns--1759230382385),type:phrase),query:(match_phrase:(ic:nr-broken-dfinity-node-head-nns--1759230382385)))),hideChart:!f,index:testnet-vector-push,interval:auto,query:(language:kuery,query:'(ic_node:%20%22host-1-host_node_exporter%22)%20and%20%22domain%22'),rowsPerPage:500,sort:!(!(timestamp,desc)))),
and the guestos service was outright failing. Now, the loop retries for
any domain creation error and retries for longer.

This does not solve the VM contention issue where the guestos service is
restarted, though (see here for a case where the retry logic was
triggered, but the VM was unsuccessfully destroyed and the service
restarted, leading to contention.