fix(IDX): libtinfo5-6.4 is no longer available in ubuntu so use 6.3 (#2858)
This is to fix the following error when entering the dev container:
```
$ ci/container/container-run.sh
...
STEP 12/77: RUN mkdir libtinfo &&     cd libtinfo &&     wget "http://security.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.4-2ubuntu0.1_amd64.deb" &&     apt -yqq install ./libtinfo5_6.4-2ubuntu0.1_amd64.deb &&     cd .. &&     rm -rf libtinfo
--2024-11-27 13:23:43--  http://security.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.4-2ubuntu0.1_amd64.deb
Resolving security.ubuntu.com (security.ubuntu.com)... 2620:2d:4002:1::103, 2620:2d:4002:1::101, 2620:2d:4000:1::102, ...
Connecting to security.ubuntu.com (security.ubuntu.com)|2620:2d:4002:1::103|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-11-27 13:23:44 ERROR 404: Not Found.

Error: error building at STEP "RUN mkdir libtinfo &&     cd libtinfo &&     wget "http://security.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.4-2ubuntu0.1_amd64.deb" &&     apt -yqq install ./libtinfo5_6.4-2ubuntu0.1_amd64.deb &&     cd .. &&     rm -rf libtinfo": error while running runtime: exit status 8
```

---------

Co-authored-by: IDX GitHub Automation <idx@dfinity.org>