fix(icp-rosetta): fix integer overflow for balances (#5401)
Balances are being stored as signed int64 in ICP Rosetta's SQLite
database. Balances, however, can go beyond INT64_MAX as they are
ultimately unsigned 64-bit integers.

We recently funded an account with more than INT64_MAX test tokens
(TESTICP), which made ICP Rosetta fail to synchronize blocks when
pointing at the TESTICP ledger:

 ```
2025-06-03T12:25:38.221738Z ERROR
rs/rosetta-api/icp/src/rosetta_server.rs:454: Error in syncing blocks:
InternalError(false, Details { error_message: Some("out of range
integral type conversion attempted | Block IDX: 3008 , Account
02dfb592f51fce16a7969f2aaf3279767679e14d2869b5819e902b3674384740, Tokens
10000000000000000000"), extra_fields: {} })
 ```
 
This PR makes rosetta store balances higher than INT64_MAX as negative
numbers (2-complement), solving the problem in a backwards compatible
way.

Tracked in [FI-1738](https://dfinity.atlassian.net/browse/FI-1738).

[FI-1738]:
https://dfinity.atlassian.net/browse/FI-1738?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ