chore: disallow ic_cdk::futures::spawn & upgrade ic_cdk to 0.18.7 (#6373)
# Description

## Disallow `ic_cdk::futures::spawn`

The new `ic_cdk::futures::spawn` method in v0.18 doesn't guarantee
immediate polling of the spawned future.
This behavior is different from the deprecated `ic_cdk::spawn` which
existing code might be relying on.

Using the new method without understanding this distinction could
introduce subtle, hard-to-debug bugs. The `ic_cdk::futures::spawn` API
works as its name implies, placing the future in the background for a
later poll by the executor, unlike the old API which would run the first
round of the future's polling immediately. This difference can lead to
unexpected execution results in existing codebases.

As suggested by the prodsec team, `ic_cdk::futures::spawn` is added to
the `disallowed-methods` list in `clippy.toml`.

Any canister code that invokes this method will get lint errors.
For example:
```rs
#[update]
fn try_disallowed_spawn() {
    ic_cdk::futures::spawn(async {});
}
```
results in
```
error: use of a disallowed method `ic_cdk::futures::spawn`
   --> rs/rust_canisters/proxy_canister/src/main.rs:284:5
    |
284 |     ic_cdk::futures::spawn(async {});
    |     ^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: This method doesn't poll immediately. For safe migration from `ic_cdk::spawn`, use `ic_cdk::futures::spawn_017_compat`. Use `#[allow(clippy::disallowed_methods)]` to locally disable this check if you understand the semantics.
```

## Upgrade to ic-cdk v0.18.7

`ic-cdk` macros for `async` canister entry-points wrap the function body
in an internal call to `ic_cdk::futures::spawn`. This would trigger the
new clippy lint rule.

In ic-cdk v0.18.7, we added `#[allow(clippy::disallowed_methods)]` to
the macro-generated code to prevent this false positive. See the
`ic-cdk` [PR](https://github.com/dfinity/cdk-rs/pull/653) for more
details.