feat(PocketIC): download PocketIC server if necessary (#4101)
This PR makes the PocketIC library download the PocketIC server binary
if necessary, i.e., if neither the function
`PocketIcBuilder::with_server_binary` nor the environment variable
`POCKET_IC_BIN` provide a path to the PocketIC server binary. The
current working directory is ignored when looking for the PocketIC
server binary.

This PR has been successfully tested on Windows, Linux, and macOS (Apple
Sillicon) by running `cargo test -p pocket-ic test_counter_canister` and
checking that the server has been started and the instances initialized
properly:
```
running 2 tests
2025-02-25T10:11:09.188867Z  INFO pocket_ic_server: The PocketIC server is listening on port 39169
Feb 25 10:11:09.316 WARN s:/n:/ic_state_manager/ic_state_manager No state available with certification.
Feb 25 10:11:09.316 WARN s:/n:/ic_query_stats/payload_builder Current stats are uninitalized. This warning should go away after some minutes if the replica is processing query calls.
Feb 25 10:11:09.322 WARN s:/n:/ic_state_manager/ic_state_manager No state available with certification.
Feb 25 10:11:09.322 WARN s:/n:/ic_query_stats/payload_builder Current stats are uninitalized. This warning should go away after some minutes if the replica is processing query calls.
```
The line in the test output
```
Failed to validate PocketIC server binary: `No such file or directory (os error 2)`. Going to download PocketIC server 7.0.0 from https://github.com/dfinity/pocketic/releases/download/7.0.0/pocket-ic-x86_64-linux.gz to the local path /tmp/pocket-ic-server-7.0.0/pocket-ic. To avoid downloads during test execution, please specify the path to the (ungzipped and executable) PocketIC server 7.0.0 using the function `PocketIcBuilder::with_server_binary` or using the `POCKET_IC_BIN` environment variable.
```
confirms that the PocketIC server has been downloaded.

It is expected that both tests fail because the latest released PocketIC
server version is not compatible with the current library:
```
thread 'test_counter_canister_async' panicked at packages/pocket-ic/src/nonblocking.rs:1433:61:
called `Result::unwrap()` on an `Err` value: (200, "Could not parse response: error decoding response body")
```