fix: filter for excluded tags in targets.py (#6528)
Previously when a PR only modified dependencies of targets that matched
the `EXCLUDED_TEST_TAGS` the `targets.py` script would return these
targets but they would then subsequently be filtered out by
`--test_tag_filters` which would cause bazel to error with:

```
ERROR: No test targets were found, yet testing was requested
```

This commit fixes that by excluding the targets matching
`EXCLUDED_TEST_TAGS` inside the `targets.py` script. If a PR only
modifies dependencies of targets matching `EXCLUDED_TEST_TAGS`
`targets.py` will return no targets causing the bazel action to exit
early and thus not invoke bazel preventing the error.