fix: --keepalive instead of --debug-keepalive in ict implementation (#8207)
This PR fixes the following error:
```
error: unexpected argument '--debug-keepalive' found

  tip: a similar argument exists: '--keepalive'
```
when running `ict t ... --keepalive`:
```
Raw Bazel command to be invoked: 
$ bazel test //rs/tests/message_routing:rejoin_test_long_rounds --test_output=streamed --cache_test_results=no --test_env=IC_DASHBOARDS_DIR=/home/ubuntu/.cache/k8s_repo/bases/apps/ic-dashboards --sandbox_add_mount_pair=/home/ubuntu/.cache/k8s_repo/bases/apps/ic-dashboards --test_timeout=3600 --test_arg=--debug-keepalive
```