chore(IDX): foundry-rs/foundry:v1.0.0 (#4764)
Bumping to new version. Previous image doesn't seem to be available
anymore:
```
Trying to pull ghcr.io/foundry-rs/foundry@sha256:d2d6a8064db8659ab4d835bd36ee4ba19a781cbe62a9729a261d7cedf3774cdd...
Error: initializing source docker://ghcr.io/foundry-rs/foundry@sha256:d2d6a8064db8659ab4d835bd36ee4ba19a781cbe62a9729a261d7cedf3774cdd: reading manifest sha256:d2d6a8064db8659ab4d835bd36ee4ba19a781cbe62a9729a261d7cedf3774cdd in ghcr.io/foundry-rs/foundry: manifest unknown
```

Relates to issue
[here](https://github.com/dfinity/ic/actions/runs/14375596503/job/40307153206).