fix: Adapt fuzzing scripts to handle new false positives (#8308)
```
ERROR: AddressSanitizer: stack-buffer-underflow on address 0x7ffd77dfc800 at pc 0x60f4e8dc115f bp 0x7ffd77dfc670 sp 0x7ffd77dfc668
WRITE of size 8 at 0x7ffd77dfc800 thread T0
SCARINESS: 57 (8-byte-write-stack-buffer-underflow)

Address 0x7ffd77dfc800 is located in stack of thread T0 at offset 0 in frame
    #0 0x60f4e91af1df  (../fuzz/execute_with_wasmtime_afl+0x5ef81df) (BuildId: ffb75432ca3d0f8f6290ad0238d7ed947ac790f0)

  This frame has 3 object(s):
    [32, 88) '_25'
    [128, 176) '_18'
    [208, 264) 'unwind'
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
```

These issues are false positives as wasmtime does custom unwinding
instead of longjmp for trampolining a while ago. This PR adapts ASan
options and compiler flags to suppress this for wasm fuzzers. Wasmtime
[PR reference](https://github.com/bytecodealliance/wasmtime/pull/11592)