chore: Bump cargo-audit to `v0.22.0` (#8165)
v0.21.0 is unable to parse any of our repo TOML files due to this CVSS
score in the dependency tree. This unfortunately blocks our dependency
scanning tool but is fixed in v0.22.0.

```
cargo audit --json
error: error loading advisory database: parse error: error parsing /home/vsekar/.cargo/advisory-db/crates/cap-primitives/RUSTSEC-2024-0445.md: parse error: TOML parse error at line 8, column 8
  |
8 | cvss = "CVSS:4.0/AV:N/AC:L/AT:P/PR:L/UI:N/VC:L/VI:L/VA:L/SC:N/SI:N/SA:N"
  |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
unsupported CVSS version: 4.0
```

---------

Co-authored-by: IDX GitHub Automation <>