fix: sync_with_vector when no local registry is available yet (#6867)
The `//rs/tests/message_routing/xnet:xnet_slo_120_subnets_staging_test`
is flaking often due to the `log_task` crashing with the following error
when it tries to [sync
vector](https://sourcegraph.com/github.com/dfinity/ic/-/blob/rs/tests/driver/src/driver/group.rs?L734)
(recent
[example](https://dash.dm1-idx1.dfinity.network/invocation/eaaae0b1-d79f-4fbb-976a-eb945d5f3548?target=%2F%2Frs%2Ftests%2Fmessage_routing%2Fxnet%3Axnet_slo_120_subnets_staging_test&targetStatus=11#@284)):
```
2025-09-19 09:03:28.268 INFO[vector_logging:rs/tests/driver/src/driver/vector_vm.rs:135:0] Syncing vector targets.
2025-09-19 09:03:28.268 INFO[vector_logging:StdErr] 
2025-09-19 09:03:28.268 INFO[vector_logging:StdErr] thread 'main' panicked at rs/tests/driver/src/driver/test_env_api.rs:1042:18:
2025-09-19 09:03:28.268 INFO[vector_logging:StdErr] Could not create local registry: EmptyRegistry
```
The reason is that `sync_with_vector()` calls `env.topology_snapshot()`
which expects that a local registry already exists on disk. However,
presumably because the testnet takes long to setup because it's is so
large, a local registry does not yet exist causing the function to
panic.

We fix this by introducing a "safe" `env.topology_snapshot()` function
called `safe_topology_snapshot()` which returns a `Result` instead of
panicking. `sync_with_vector()` is adapted to call
`env.safe_topology_snapshot()?` such that the `log_task` simply retries
when it fails.