fix(IDX): docker.io auth (#224)
`sudo podman` doesn't seem to get credentials. Adding them to
`.docker/auth.json` for root which is the file that rootful podman uses
as a fallback if it exists.
```
Error: initializing source docker://dfinity/boundaryos-base@sha256:8c218ad124309aa177c2f41c3766f87edca4485150c4ebe002de281a6932ae83: reading manifest sha256:8c218ad124309aa177c2f41c3766f87edca4485150c4ebe002de281a6932ae83 in docker.io/dfinity/boundaryos-base: toomanyrequests: You have reached your pull rate limit.
```