feat: Tool to verify key resharing recovery proposal (#5297)
Usage:
```bash
ci/container/container-run.sh

# Download and print CUPs of all nodes on the subnet, store the latest one as /ic/cup.pb
bazel run rs/cup_explorer:cup_explorer_bin -- --nns-url https://ic0.app explore --subnet-id fuqsr-in2lc-zbcjj-ydmcw-pzq7h-4xm2z-pto4i-dcyee-5z4rz-x63ji-nae --download-path /ic/cup.pb

# Verify a local CUP file
bazel run rs/cup_explorer:cup_explorer_bin -- --nns-url https://ic0.app verify-cup-of-halted-subnet --cup-path /ic/cup.pb
```

Example Output:
```
INFO: Running command line: bazel-bin/rs/cup_explorer/cup_explorer_bin verify --cup-path /ic/cup.pb
NNS public key being used: 
-----BEGIN PUBLIC KEY-----
MIGCMB0GDSsGAQQBgtx8BQMBAgEGDCsGAQQBgtx8BQMCAQNhAIFMDm7HH6tYOwi9
gTc8JVw8NxsuhIY8mKTx4It0I10U+12cDNVG2WhfkToMCyzFNBWDv0tDkuRn25bW
W5u0y3FxEvhHLg1aTRRQX/10hLASkQkcX4e5iINGP5gJGguqrg==
-----END PUBLIC KEY-----

Registry client created. Latest registry version: 50706

Creating crypto component...
May 27 09:44:41.133 INFO s:/n:/ic_crypto_internal_csp/vault Proceeding with an in-replica csp_vault, CryptoConfig: CryptoConfig { crypto_root: "/tmp/ic_crypto_i3xZMF", csp_vault_type: InReplica }
Getting registry value of key crypto_record_zqig3-p7rnb-j42zi-p7hci-ktjc7-4oxmo-p4ujh-itwj3-xmdtl-5ve3t-aqe_1 at version 50706...
Getting registry value of key crypto_record_zqig3-p7rnb-j42zi-p7hci-ktjc7-4oxmo-p4ujh-itwj3-xmdtl-5ve3t-aqe_4 at version 50706...
Getting registry value of key crypto_tls_cert_zqig3-p7rnb-j42zi-p7hci-ktjc7-4oxmo-p4ujh-itwj3-xmdtl-5ve3t-aqe at version 50706...
Getting registry value of key crypto_record_zqig3-p7rnb-j42zi-p7hci-ktjc7-4oxmo-p4ujh-itwj3-xmdtl-5ve3t-aqe_3 at version 50706...
Getting registry value of key crypto_record_zqig3-p7rnb-j42zi-p7hci-ktjc7-4oxmo-p4ujh-itwj3-xmdtl-5ve3t-aqe_5 at version 50706...

Reading CUP file at "/ic/cup.pb"
CUP integrity verified!

Checking CUP signature for subnet fuqsr-in2lc-zbcjj-ydmcw-pzq7h-4xm2z-pto4i-dcyee-5z4rz-x63ji-nae...
Getting registry value of key catch_up_package_contents_fuqsr-in2lc-zbcjj-ydmcw-pzq7h-4xm2z-pto4i-dcyee-5z4rz-x63ji-nae at version 50690...
CUP signature verification successful!

Latest subnet state according to CUP:
                TIME: 1748271343192946614, (2025-05-26 14:55:43.192946614 UTC)
              HEIGHT: 143603500
                HASH: c214b0175f2348a28a0bb9b63b46d9502cec8071974a370559edbb7ab481b569
    REGISTRY VERSION: 50690

Verifying that the subnet was halted on this CUP...
Getting registry value of key subnet_record_fuqsr-in2lc-zbcjj-ydmcw-pzq7h-4xm2z-pto4i-dcyee-5z4rz-x63ji-nae at version 50690...

thread 'main' panicked at rs/cup_explorer/src/main.rs:220:5:
Verification failed: Subnet wasn't instructed to halt on this CUP. Therefore, this CUP is NOT guaranteed to represent the latest state of the subnet!
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

How to reproduce on a testnet:
Alternatively, run the system test: `ict test
//rs/tests/consensus:cup_explorer_test`

1. I recommend reducing the DKG interval length of the `small` testnet
by adapting its setup function
2. Build `ic-admin` and `cup_explorer`:
```bash
bazel build rs/registry/admin:ic-admin
bazel build rs/cup_explorer:cup_explorer_bin
```
3. Start a testnet:
```bash
rm -rf ./small && ict testnet create //rs/tests/testnets:small_head_nns --lifetime-mins=180 --output-dir=./small -- --test_tmpdir=./small
```
4. Extract `NNS_IP` and `SUBNET_ID`:
```bash
NNS_IP=<IP of NNS node>
SUBNET_ID=<subnet ID of app subnet>
```
5. Halt App subnet at the next CUP height:
```bash
bazel-bin/rs/registry/admin/ic-admin --nns-url http://[$NNS_IP]:8080 propose-to-update-subnet --subnet $SUBNET_ID --test-neuron-proposer --halt-at-cup-height true --summary "Halt at CUP height"
```
6. Wait until subnet has halted
7. Download the latest CUP:
```bash
bazel-bin/rs/cup_explorer/cup_explorer_bin --nns-url http://[$NNS_IP]:8080 --nns-pem ./small/_tmp/*/setup/ic_prep/nns_public_key.pem explore --subnet-id $SUBNET_ID --download-path /ic/cup.pb
```
8. Verify the CUP. The tool should return that the subnet was halted,
and how to choose parameters to recover it:
```bash
bazel-bin/rs/cup_explorer/cup_explorer_bin --nns-url http://[$NNS_IP]:8080 --nns-pem ./small/_tmp/*/setup/ic_prep/nns_public_key.pem verify-cup-of-halted-subnet --cup-path /ic/cup.pb
```
9. Determine recovery parameters using the tool's output:
```bash
STATE_HASH=...
HEIGHT=...
TIME=...
```
10. Recover the subnet:
```bash
bazel-bin/rs/registry/admin/ic-admin --nns-url "http://[$NNS_IP]:8080" \
  propose-to-update-recovery-cup \
  --subnet-index $SUBNET_ID \
  --height $HEIGHT \
  --state-hash $STATE_HASH \
  --time-ns $TIME \
  --summary "Recover Subnet" \
  --test-neuron-proposer
```
11. Once the proposal was executed, run verification again. The tool
should now print that the subnet was recovered using the correct
parameters:
```bash
bazel-bin/rs/cup_explorer/cup_explorer_bin --nns-url http://[$NNS_IP]:8080 --nns-pem ./small/_tmp/*/setup/ic_prep/nns_public_key.pem verify-cup-of-halted-subnet --cup-path /ic/cup.pb
```

---------

Co-authored-by: IDX GitHub Automation <infra+github-automation@dfinity.org>