fix(repro-check): use temp dir in the home directory to fix cross-device linking issue (#5167)
Fix:

On some machines the repro-check script was throwing an error:
```
OSError: [Errno 18] Invalid cross-device link: '/home/...<path1>/update-img.tar.zst' -> '/tmp/<path2>/update-img.tar.zst'
```

This was because on some machines `/home` and `/tmp` are on different
file systems.
The fix is to create temporary directory under `base_cache_dir` with
timestamp instead of `tempfile.TemporaryDirectory`