fix(IDX): make launch-remote-vm testonly because it depends on a testonly target
This fixes the following error:

```
$ bazel build //ic-os/guestos/envs/prod:launch-remote-vm --config=check
INFO: Invocation ID: 713803fa-c204-4f6c-8638-523a043c58a4
INFO: Streaming build results to: https://dash.idx.dfinity.network/invocation/713803fa-c204-4f6c-8638-523a043c58a4
INFO: Build option --@rules_rust//rust/settings:pipelined_compilation has changed, discarding analysis cache.
ERROR: /ic/ic-os/guestos/envs/prod/BUILD.bazel:10:11: in genrule rule //ic-os/guestos/envs/prod:launch-remote-vm: non-test target '//ic-os/guestos/envs/prod:launch-remote-vm' depends on testonly target '//rs/ic_os/launch-single-vm:launch-single-vm' and doesn't have testonly attribute set
ERROR: /ic/ic-os/guestos/envs/prod/BUILD.bazel:10:11: Analysis of target '//ic-os/guestos/envs/prod:launch-remote-vm' failed
ERROR: Analysis of target '//ic-os/guestos/envs/prod:launch-remote-vm' failed; build aborted:
INFO: Elapsed time: 4.102s
INFO: 0 processes.
INFO: Streaming build results to: https://dash.idx.dfinity.network/invocation/713803fa-c204-4f6c-8638-523a043c58a4
FAILED: Build did NOT complete successfully (1206 packages loaded, 48009 targets configured)
```