fix: add missing large testnet runtime dependency (#468)
Creating a large testnet currently fails with 
```
Analyzing: target //rs/tests/testing_verification/testnets:large (0 packages loaded, 0 targets configured)
ERROR: /ic/rs/tests/testing_verification/testnets/BUILD.bazel:157:12: in run_system_test rule //rs/tests/testing_verification/testnets:large: label '//rs/rosetta-api/icrc1/ledger:ledger_canister' in $(location) expression is not a declared prerequisite of this rule
ERROR: /ic/rs/tests/testing_verification/testnets/BUILD.bazel:157:12: Analysis of target '//rs/tests/testing_verification/testnets:large' failed
ERROR: Analysis of target '//rs/tests/testing_verification/testnets:large' failed; build aborted:
```

This MR adds the ledger canister to the runtime depndencies.